# Generated by Django 3.1.1 on 2020-09-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mac', models.CharField(max_length=100)),
                ('Auth0_Token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.CharField(max_length=10000)),
                ('Url', models.URLField(max_length=500)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse_Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Element', models.CharField(max_length=100)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Delete_From_The_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Url', models.URLField(max_length=500)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Qty', models.CharField(max_length=100)),
                ('Soldby', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ShipSpeed', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=250)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Url', models.URLField(max_length=500)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Url', models.URLField(max_length=500)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session+', to='api.session')),
            ],
        ),
    ]
