# Generated by Django 3.1.1 on 2020-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Soldby',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
