# Generated by Django 3.1.1 on 2020-09-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200924_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='Url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Soldby',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='delete_from_the_cart',
            name='Url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Url',
            field=models.CharField(max_length=500),
        ),
    ]
